version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: local-postgresql
    ports:
    - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgresondocker"
      POSTGRES_PASSWORD: "postgresondocker"
      POSTGRES_DB: "postgresondocker"
  api:
    build: .
    ports:
      - 8080:8080